apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  namespace: demo
  labels:
    app: cpu-stress
spec:
  containers:
    - name: cpu-stress
      image: containerstack/cpustress
      args:
        - --cpu
        - "2"
        - --timeout
        - "600s"
        - --metrics-brief
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi